name: cicd pipeline
on:
    push:
        branches: - main
        pull_request:
            branches: -main

        jobs: 
            build: 
                name: build And Test
                runs-on: ubuntu-latest

                strategy:
                    matrix:
                        node-version: [14.x, 16.x, 18.x]
                        os: [ubuntu-latest, windows-latest, macos-latest]

                        steps:
                            -name: Checkout Repository
                            uses: actions/checkout@v4

                            -name: Setup Nodejs
                            uses: actions/setup-node@v4
                            with: 
                                node-version: ${{matrix.node-version}}
                            -name: install Dependency
                            uses: npm install
                            
                            -name: Run Test
                            uses: npm test -if--present

            
